"""儲存層介面：本機用記憶體版，Google Cloud 用 Firestore 版，業務程式碼不必改。"""
from __future__ import annotations

from typing import Any, Protocol

from app.models import Case, CaseStatus


class CaseRepository(Protocol):
    async def create_case(self) -> Case: ...
    async def get(self, case_id: str) -> Case | None: ...
    async def get_by_token(self, token: str) -> Case | None: ...
    async def update(self, case_id: str, **fields: Any) -> Case | None: ...
    async def transition(self, case_id: str, expect: CaseStatus, **fields: Any) -> Case | None:
        """原子操作：只有目前狀態等於 expect 才寫入；否則不寫入並回傳 None（找不到案件也是 None）。"""
        ...
    async def list_cases(self, limit: int = 100, status: CaseStatus | None = None,
                         offset: int = 0) -> list[Case]: ...
    async def list_by_owner(self, email: str, limit: int = 200) -> list[Case]: ...
    async def delete(self, case_id: str) -> bool: ...
    async def append_event(self, case_id: str, event: dict) -> None: ...
    async def list_events(self, case_id: str) -> list[dict]: ...
